### ISSUE TITLE
Add topic tags

### ISSUE THREAD

**Issue by Beliavsky** [MomoInSpace/FortranHPC#4]
I suggest adding topics such as `fortran`, `hpc`, `mpi`, `cuda`, `openacc`, `cuda-fortran` in the About section, as explained at https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by MomoInSpace** [comment]
Thanks for the suggestion!
